name: Atualizar Dados Diariamente

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  atualizar-json:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar os arquivos do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Rodar o script Python
        env:
          PLANILHA_URL: ${{ secrets.PLANILHA_URL }}
        run: python atualizar_dados.py

      - name: Salvar novo arquivo JSON
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"
          git add dados.json
          git commit -m "🤖 Atualização diária dos dados da monitoria" || exit 0
          git push
